-- CREATE DATABASE IF NOT EXISTS MartaTraffic;
-- USE MartaTraffic;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
	Username			VARCHAR(25) 	NOT NULL,
	Password 			VARCHAR(25)		NOT NULL,
	IsAdmin				BOOLEAN			NOT NULL,
	CONSTRAINT USER_PK
		PRIMARY KEY (Username)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS PASSENGER;
CREATE TABLE PASSENGER
(
	Username			VARCHAR(25)		NOT NULL,
	Email				VARCHAR(50)		NOT NULL,
	CONSTRAINT PASENGER_PK
		PRIMARY KEY (Username),
	CONSTRAINT PASSENGER_UNIQUE
		UNIQUE (Email),
	CONSTRAINT PASENGER_FK
		FOREIGN KEY (Username) REFERENCES USER(Username)
			ON DELETE CASCADE 	ON UPDATE CASCADE
) ENGINE = InnoDB;


DROP TABLE IF EXISTS BREEZECARD;
CREATE TABLE BREEZECARD
(
	Card_ID		 		CHAR(16) 		NOT	NULL,
	Balance 			DECIMAL(6, 2) 	NOT NULL,
	Passenger_Username 	VARCHAR(25),    
	Suspended_Status	BOOLEAN			NOT NULL,
	CONSTRAINT BREEZECARD_PK
		PRIMARY KEY (Card_ID),
	CONSTRAINT BREEZECARD_VALUE
		CHECK (Balance >= 0 and Balance <= 1000),
	CONSTRAINT BREEZECARD_FK
		FOREIGN KEY (Passenger_Username) REFERENCES PASSENGER (Username)
			ON DELETE SET NULL 		ON UPDATE CASCADE
) ENGINE = InnoDB;


DROP TABLE IF EXISTS STATION;
CREATE TABLE STATION
(
	StopID 				VARCHAR(30) 	NOT NULL,
	Station_Name		VARCHAR(30)		NOT NULL,
	Station_Type		VARCHAR(5)		NOT NULL,
	Enter_Fare 			DECIMAL(4, 2) 	NOT NULL,
	Station_Status 		BOOLEAN			NOT NULL,
	CONSTRAINT STATION_PK
		PRIMARY KEY (StopID),
	CONSTRAINT STATION_UNIQUE
		UNIQUE (Station_Name, Station_Type),
	CONSTRAINT STATION_FARE
		CHECK (Enter_Fare >= 0 and Enter_Fare <= 50)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS BUSSTATION;
CREATE TABLE BUSSTATION
(
	Station_StopID 		VARCHAR(30) 	NOT NULL,
	Intersection 		VARCHAR(30),
	CONSTRAINT BUSSTATION_PK
		PRIMARY KEY (Station_StopID),
	CONSTRAINT BUSSTATION_FK
		FOREIGN KEY (Station_StopID) REFERENCES STATION (StopID)
			ON DELETE CASCADE 	ON UPDATE CASCADE
) ENGINE = InnoDB;


DROP TABLE IF EXISTS TRIP;
CREATE TABLE TRIP
(
	Start_Time 			TIMESTAMP 		NOT NULL,
	Fare 				DECIMAL(4, 2) 	NOT NULL,
	BCNumber 			CHAR(16) 		NOT NULL,
	StartsAt			VARCHAR(30)		NOT NULL,
	EndsAt				VARCHAR(30),
	CONSTRAINT TRIP_PK
		PRIMARY KEY (Start_Time, BCNumber),
	CONSTRAINT TRIP_FK_ONE
		FOREIGN KEY (BCNumber) REFERENCES BREEZECARD (Card_ID)
			ON DELETE CASCADE 	ON UPDATE CASCADE,
	CONSTRAINT TRIP_FK_TWO
		FOREIGN KEY (StartsAt) REFERENCES STATION (StopID)
			ON DELETE CASCADE 	ON UPDATE CASCADE,
	CONSTRAINT TRIP_FK_THREE
		FOREIGN KEY (EndsAt) REFERENCES STATION (StopID)
			ON DELETE CASCADE 	ON UPDATE CASCADE
) ENGINE = InnoDB;


DROP TABLE IF EXISTS CONFLICT;
CREATE TABLE CONFLICT
(
	Passenger_Username 	VARCHAR(25)		NOT NULL,
	BCNumber 			CHAR(16) 		NOT NULL,
	Suspended_Time 		DATE			NOT NULL,
	CONSTRAINT CONFLICT_PK
		PRIMARY KEY (Passenger_Username, BCNumber),
	CONSTRAINT CONFLICT_FK_1
		FOREIGN KEY (Passenger_Username) REFERENCES PASSENGER (Username)
			ON DELETE CASCADE 	ON UPDATE CASCADE,
	CONSTRAINT CONFLICT_FK_2
		FOREIGN KEY (BCNumber) REFERENCES BREEZECARD (Card_ID)
			ON DELETE CASCADE 	ON UPDATE CASCADE
) ENGINE = InnoDB;