CREATE TABLE USER
(
	Username	VARCHAR(25) 	NOT NULL,
	Password 	VARCHAR(25)		NOT NULL,
	CONSTRAINT USERPK
		PRIMARY KEY (Username),
);

CREATE TABLE PASSENGER
(
	Passenger_Username	VARCHAR(25)		NOT NULL,
	Email				VARCHAR(50)		NOT NULL,
	CONSTRAINT PASPK
		PRIMARY KEY (Passenger_Username),
	CONSTRAINT PASPEUNI
		UNIQUE (Email)
		CHECK (Email like '^[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$'), # put check here??
	CONSTRAINT PASPUFK
		FOREIGN KEY ('Passenger_Username') REFERENCES USER('Username')
			ON DELETE CASCADE 	ON UPDATE CASCADE
);

/*
password at least 8 charaters
*/

CREATE TABLE BREEZECARD
(
	Card_ID		 		INT 			NOT	NULL,
	Balance 			DECIMAL(6, 2), 	NOT NULL,
	Passenger_Username 	VARCHAR(25),    # no need to add "DEFAULT NULL"
	Suspended_Status	BOOLEAN			NOT NULL,
	CONSTRAINT BCPK
		PRIMARY KEY (Card_ID),
	CONSTRAINT BCV
		CHECK (Balance >= 0 and Balance <= 1000),
	CONSTRAINT BCPUFK
		FOREIGN KEY ('Passenger_Username') REFERENCES PASSENGER ('Passenger_Username')
			ON DELETE SET NULL 	ON UPDATE CASCADE
);

CREATE TABLE STATION
(
	StopID 				INT 			NOT NULL,
	Name				VARCHAR(30)		NOT NULL,
	Station_Type		VARCHAR(5),		NOT NULL,
	Enter_Fare 			DECIMAL(4, 2), 	NOT NULL,
	Station_Status 		BOOLEAN			NOT NULl,
	CONSTRAINT STAIDPK
		PRIMARY KEY (StopID),
	CONSTRAINT STFARE
		CHECK (Enter_Fare >= 0 and Enter_Fare <= 50)
);

CREATE TABLE BUSSTATION
(
	Bus_Station_Name 	VARCHAR(30) 	NOT NULL,
	Station_StopID 		INT 			NOT NULL,
	Intersection 		VARCHAR(30),
	CONSTRAINT BSTAPK
		PRIMARY KEY (Bus_Station_Name, Station_StopID),
	CONSTRAINT BSTAIDFK
		FOREIGN KEY ('Station_StopID') REFERENCES STATION ('StopID')
			ON DELETE CASCADE 	ON UPDATE CASCADE
);


CREATE TABLE TRIP
(
	Start_Time 		TIMESTAMP 		NOT NULL,
	Current_Fare 	DECIMAL(4, 2), 	NOT NULL,
	BCNumber 		INT 			NOT NULL,
	Station_StopID 	INT, 			NOT NULL,
	CONSTRAINT TRPK
		PRIMARY KEY (Start_Time, BCNumber)
	CONSTRAINT TRIDFK
		FOREIGN KEY ('Station_StopID') REFERENCES STATION ('StopID')
			ON DELETE CASCADE 	ON UPDATE CASCADE,
	CONSTRAINT TRBCNFK
		FOREIGN KEY ('BCNumber') REFERENCES BREEZECARD ('card_Number')
			ON DELETE CASCADE 	ON UPDATE CASCADE
);

CREATE TABLE CONFLICT
(
	Passenger_Username 	VARCHAR(25)		NOT NULL,
	BCNumber 			INT 			NOT NULL,
	date_Time 			DATE,			NOT NULL,
	CONSTRAINT CONPK
		PRIMARY KEY (Passenger_Username, BCNumber),
	CONSTRAINT CONEMFK
		FOREIGN KEY ('Passenger_Username') REFERENCES PASSENGER ('Passenger_Username')
			ON DELETE CASCADE 	ON UPDATE CASCADE,
	CONSTRAINT CONBCNFK
		FOREIGN KEY ('BCNumber') REFERENCES BREEZECARD ('Card_ID')
			ON DELETE CASCADE 	ON UPDATE CASCADE
);